spring.application.name=taskmanager
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=taskdb
server.port=8080

# Enable 404 exception handling
spring.mvc.throw-exception-if-no-handler-found=true

# JWT Properties
app.jwtSecret=a03522e8c810fe2d81ff7943614adcc3dd6263edba6c5206a024f15729ef6b67
#app.jwtExpirationMs=3600000
#app.jwtExpirationMs=300000
app.jwtExpirationMs=100000
app.jwtRefreshExpirationMs=86400000

# Redis Properties
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging Configuration
logging.level.root=INFO
logging.level.com.example.taskmanager=DEBUG
logging.file.name=logs/taskmanager.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=30
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
