spring.application.name=taskmanager
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=taskdb
server.port=8080

# JWT Properties
app.jwtSecret=a03522e8c810fe2d81ff7943614adcc3dd6263edba6c5206a024f15729ef6b67
app.jwtExpirationMs=3600000
app.jwtRefreshExpirationMs=86400000

# Redis Properties
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Enable NoHandlerFoundException
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
